# @Author: Rachith Aiyappa
# @Date: 2025-04-30

INSTRUCTION_TEMPLATES = {
    "1": "Your response to the question should be either {op1}, {op2}, or {op3}.",
    "2": "The question needs to be answered with either {op1}, {op2}, or {op3}.",
    "3": "Kindly provide your answer to the question in the format of {op1}, {op2}, or {op3}.",
    "4": "To provide your response to the question, you need to select {op1}, {op2}, or {op3}.",
    "5": "The question requires a response in the form of {op1}, {op2}, or {op3}.",
    "6": "Kindly respond to the question using {op1}, {op2}, or {op3}.",
    "7": "Please select one of {op1}, {op2}, or {op3} when answering the question.",
    "8": "In order to answer the question, you must select either {op1}, {op2}, or {op3}.",
    "9": "To provide your response to the question, please select {op1}, {op2}, or {op3}.",
}

PROMPT_TEMPLATES = {
    "1": "{instruction}\n\nStatement: {tweet}\nQuestion: What is the attitude of the statement to {target}?",
    "2": "{instruction}\n\nStatement: {tweet}\nQuestion: What is the stance of the statement to {target}?",
    "3f": "{instruction}\n\nStatement: {tweet}\nQuestion: The statement is in favor of {target}.",
    "3a": "{instruction}\n\nStatement: {tweet}\nQuestion: The statement is against {target}.",
    "4f_not": "{instruction}\n\nStatement: {tweet}\nQuestion: The statement is not in favor of {target}.",
    "4a_not": "{instruction}\n\nStatement: {tweet}\nQuestion: The statement is not against {target}.",
}

INSTRUCTION_OPTIONS = {
    "1": ["positive", "negative", "neutral"],
    "2": ["favor", "against", "neutral"],
    "3f": ["true", "false", "neutral"],
    "3a": ["true", "false", "neutral"],
    "4f_not": ["true", "false", "neutral"],
    "4a_not": ["true", "false", "neutral"],
}

FLANT5_TOKENS = {
    "1": [
        "Positive",
        "Negative",
        "Neutral",
        "Positive.",
        "Negative.",
        "Neutral.",
        "positive",
        "negative",
        "neutral",
        "positive.",
        "negative.",
        "neutral.",
    ],
    "2": [
        "Favor",
        "Against",
        "Neutral",
        "Favor.",
        "Against.",
        "Neutral.",
        "favor",
        "against",
        "neutral.",
        "favor.",
        "against.",
        "neutral.",
    ],
    "3f": [
        "True",
        "False",
        "Neutral",
        "True.",
        "False.",
        "Neutral.",
        "true",
        "false",
        "neutral",
        "true.",
        "false.",
        "neutral.",
    ],
    "3a": [
        "True",
        "False",
        "Neutral",
        "True.",
        "False.",
        "Neutral.",
        "true",
        "false",
        "neutral",
        "true.",
        "false.",
        "neutral.",
    ],
    "4f_not": [
        "True",
        "False",
        "Neutral",
        "True.",
        "False.",
        "Neutral.",
        "true",
        "false",
        "neutral",
        "true.",
        "false.",
        "neutral.",
    ],
    "4a_not": [
        "True",
        "False",
        "Neutral",
        "True.",
        "False.",
        "Neutral.",
        "true",
        "false",
        "neutral",
        "true.",
        "false.",
        "neutral.",
    ],
}
